name: product-service-ci

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:

  validation:
    uses: shopmesh/shared-workflows-template/.github/workflows/validation-ci.yaml@main
    with:
      service_name: product-service
      service_path: .
      runtime: node
      github_event_name: ${{ github.event_name }}
    secrets: inherit

  build:
    needs: validation
    uses: shopmesh/shared-workflows-template/.github/workflows/generate-tag-and-build-image-trivy.yaml@main
    with:
      service_name: product-service
      service_path: .
      run_trivy: true
    secrets: inherit

  push:
    needs: build
    if: github.event_name == 'push'
    uses: shopmesh/shared-workflows-template/.github/workflows/push.yaml@main
    with:
      service_name: product-service
      git_tag: ${{ needs.build.outputs.tag }}
      tag_exists: ${{ needs.build.outputs.tag_exists }}
    secrets: inherit
