name: product-service

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref_name == 'develop')
    uses: shopmesh/shared-workflows-template/.github/workflows/code-quality.yml@main
    with:
      service_name:      product-service
      service_path:      .
      runtime:           node
      github_event_name: ${{ github.event_name }}
    secrets:
      SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN:     ${{ secrets.SNYK_TOKEN }}

  build:
    needs: code-quality
    if: always() && (needs.code-quality.result == 'success' || needs.code-quality.result == 'skipped')
    uses: shopmesh/shared-workflows-template/.github/workflows/build.yml@main
    with:
      service_name: product-service
      service_path: .
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}

  helm:
    needs: build
    if: github.ref_name == 'main' && github.event_name == 'push' && needs.build.result == 'success'
    uses: shopmesh/shared-workflows-template/.github/workflows/helm.yml@main
    with:
      service_name: product-service
      image_tag:    ${{ needs.build.outputs.tag }}
      helm_repo:    shopmesh/shopmesh-infra
    secrets:
      HELM_CHARTS_TOKEN: ${{ secrets.HELM_CHARTS_TOKEN }}

  notify:
    needs: [code-quality, build, helm]
    if: failure()
    uses: shopmesh/shared-workflows-template/.github/workflows/notify.yml@main
    with:
      service_name: product-service
    secrets:
      SENDGRID_API_KEY:  ${{ secrets.SENDGRID_API_KEY }}
      NOTIFY_FROM_EMAIL: ${{ secrets.NOTIFY_FROM_EMAIL }}
      NOTIFY_TO_EMAIL:   ${{ secrets.NOTIFY_TO_EMAIL }}